#!/bin/bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "${REPO_ROOT}"

# Labeled programming data generated by examples/programming/label_test_cases.py
DATA1="${REPO_ROOT}/code/Reward-Hacking-main/examples/programming/data/all_labeled/data_1-4_tstMin6_tstMax50.jsonl"
DATA2="${REPO_ROOT}/code/Reward-Hacking-main/examples/programming/data/all_labeled/data_5-10_tstMin6_tstMax50.jsonl"

MODEL="${MODEL:-Qwen/Qwen2.5-3B-Instruct}"
OUTPUT_DIR="${OUTPUT_DIR:-${REPO_ROOT}/train/output/codegen_grpo_run1}"
REWARD_URL="${REWARD_URL:-http://localhost:8118/batched_unittest}"

# Requires reward API running in examples/programming/reward_api.py
accelerate launch --num_processes 4 -m train.codegen.grpo_codegen_train \
  --data "${DATA1}" "${DATA2}" \
  --model "${MODEL}" \
  --output_dir "${OUTPUT_DIR}" \
  --reward_url "${REWARD_URL}" \
  --deepspeed_cfg "${REPO_ROOT}/train/ds_zero3.json"
